name: "Python Container Action Template"
description: "Get started with Python Gradle actions"
author: "Shruthi Sridharan"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"