name: gradle-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Create a gradle wrapper
        run: gradle wrapper --gradle-version 3.0
      - name: Build with Gradle
        run: ./gradlew build
