name: gradle-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run with setup-python 3.5
        uses: ./
        with:
          python-version: 3.5
      - name: Verify 3.5
        run: python test/test_example.py 3.5
